### ISSUE TITLE
插帧问题

### ISSUE THREAD

**Issue by sove45** [HebeiFast/EventLowLightVOS#10]
![image](https://github.com/user-attachments/assets/3a925a29-b9c1-4f03-aadf-f1106f944276)
https://github.com/google-research/frame-interpolation
FILMGitHub主页如上，作者说输出帧的扩充倍数如下
![image](https://github.com/user-attachments/assets/7da5619f-7562-47f3-9066-bdedf65920b0)
所以25fps也不能扩充到100fps
麻烦您分享一下times_to_interpolat所采用的值

**Comment by HebeiFast** [comment]
你可以参照这个event生成的库进行实现：https://github.com/uzh-rpg/rpg_vid2e

**Comment by sove45** [comment]
> 你可以参照这个event生成的库进行实现：https://github.com/uzh-rpg/rpg_vid2e

感谢您的帮助，我将复现这个代码进行尝试
