### ISSUE TITLE
event模态数据格式问题

### ISSUE THREAD

**Issue by sove45** [HebeiFast/EventLowLightVOS#11]
你好，我使用了PIL+numpy读取了RGB模态图像，并使用numpy load了这张图片配对的event模态的.npy矩阵，但是
![8a15141026d24e8474424bd96b6870d](https://github.com/user-attachments/assets/64bef7b2-f49c-4d2e-8a7b-28e734bdfa91)
所读出来的event模态是一个(8510, 4)的矩阵RGB模态是一个(260,346, 3)的矩阵，请问如何把event模态转换成event相关任务中常见的.png格式呢（如论文中展示的这样）
![f694168f5c66bce6ba8837a0a1cf0efa](https://github.com/user-attachments/assets/5ce9674a-1b5f-4a58-a3b5-7156436d873b)

**Comment by sove45** [comment]
问题已解决，打扰了：）

**Comment by whistle-blower-kingdom** [comment]
@sove45 能共享下吗？也有这样的问题
