### ISSUE TITLE
A question about memory bank

### ISSUE THREAD

**Issue by xhowdonewd** [HebeiFast/EventLowLightVOS#4]
Thank you for your great work. I have some doubts about the memory bank. I don’t know the specific internal implementation. There seems to be no specific explanation in the article. Where can I see the relevant content? Will the code to be released include this part?
:)

**Comment by HebeiFast** [comment]
In our paper, memory bank is a container to store the five previous features for matching process.

**Comment by HebeiFast** [comment]
After AAAI, I will publish the code gradually.
