### ISSUE TITLE
数据集下载所遇到的困难

### ISSUE THREAD

**Issue by sove45** [HebeiFast/EventLowLightVOS#6]
您好，我在使用您所发布的下载链接来下载数据集的过程中遇到了下载带宽仅为10k的问题，并且多次在下载到6G的时候因为网络问题中断，多次切换节点和换网络环境仍然没有改善，但是我在使用谷歌云盘来下载其他数据集的收并没有出现这种情况。
我猜测是因为您使用了谷歌云盘的镜像，而镜像会限速，希望您可以公布一下谷歌云盘的直接下载链接

**Comment by HebeiFast** [comment]
我没用Google镜像加速，我最近处理一下，传到其他网盘看看，毕竟我上传也好慢







李和倍


Phone: (+86)13023059058
Email: ***@***.***
-----原始邮件-----
发件人:sove45 ***@***.***>
发送时间:2024-09-09 13:11:26 (星期一)
收件人: HebeiFast/EventLowLightVOS ***@***.***>
抄送: Subscribed ***@***.***>
主题: [HebeiFast/EventLowLightVOS] 数据集下载所遇到的困难 (Issue #6)






您好，我在使用您所发布的下载链接来下载数据集的过程中遇到了下载带宽仅为10k的问题，并且多次在下载到6G的时候因为网络问题中断，多次切换节点和换网络环境仍然没有改善，但是我在使用谷歌云盘来下载其他数据集的收并没有出现这种情况。
我猜测是因为您使用了谷歌云盘的镜像，而镜像会限速，希望您可以公布一下谷歌云盘的直接下载链接

**Comment by sove45** [comment]
> 我没用Google镜像加速，我最近处理一下，传到其他网盘看看，毕竟我上传也好慢 李和倍 Phone: (+86)13023059058 Email: ***@***.*** -----原始邮件----- 发件人:sove45 ***@***.***> 发送时间:2024-09-09 13:11:26 (星期一) 收件人: HebeiFast/EventLowLightVOS ***@***.***> 抄送: Subscribed ***@***.***> 主题: [HebeiFast/EventLowLightVOS] 数据集下载所遇到的困难 (Issue #6) 您好，我在使用您所发布的下载链接来下载数据集的过程中遇到了下载带宽仅为10k的问题，并且多次在下载到6G的时候因为网络问题中断，多次切换节点和换网络环境仍然没有改善，但是我在使用谷歌云盘来下载其他数据集的收并没有出现这种情况。 我猜测是因为您使用了谷歌云盘的镜像，而镜像会限速，希望您可以公布一下谷歌云盘的直接下载链接 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

非常感谢,请问您能否公开一下LLE-DAVIS数据集,我在复现的时候遇到了困难

**Comment by HebeiFast** [comment]
我暂时不会公开LLE-DAVIS，整个数据集生成之后还是比较大的。 如果你有任何复现困难，可以与我联系。
