### ISSUE TITLE
Black border on normal light images in the dataset

### ISSUE THREAD

**Issue by JoanneLin168** [HebeiFast/EventLowLightVOS#7]
Hi there, I wanted to know why there's a black border on the top and right sides of the normal light images?

**Comment by HebeiFast** [comment]
Hi, the black border on the top and right sides of the normal light images is caused by the calibration matrix used for correction. This process adjusts the image geometry, which can result in portions of the image being shifted outside the visible frame, leaving black areas in those regions.
