### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by sove45** [HebeiFast/EventLowLightVOS#8]
作者你好,请问您能否公开一下所生成的LLE-DAVIS数据集,以及在LLE-DAVIS和LLE-VOS数据集上的训练测试集分划以及在LLE-DAVIS数据集上Indoor Scenes 和Outdoor Scenes上的分划

**Comment by HebeiFast** [comment]
LLE-DAVIS并有没有进行Indoor和Outdoor划分。LLE-VOS的划分会在稍后给出。 LLE-DAVIS我们暂时不会公开。

**Comment by sove45** [comment]
> LLE-DAVIS并有没有进行Indoor和Outdoor划分。LLE-VOS的划分会在稍后给出。 LLE-DAVIS我们暂时不会公开。

在论文中
![a4ebaf00ef67b4a91d801fd3ec086756](https://github.com/user-attachments/assets/625e3954-b5ef-4b00-9520-acad36d2bdf8)
有提到先将davis数据集插值到100fps，我注意到DAVIS是一个24FPS的数据集，然而FILM插帧只能实现2^n+1倍的插帧，所以FILM插帧不能把24FPS的视频插帧到100FPS
