### ISSUE TITLE
数据集复现问题

### ISSUE THREAD

**Issue by sove45** [HebeiFast/EventLowLightVOS#9]
在论文中
![image](https://github.com/user-attachments/assets/b7b1fbc3-219a-4470-a7fa-2caa1dfecaad)
有提到先将davis数据集插值到100fps，我注意到DAVIS是一个24FPS的数据集，然而FILM插帧只能实现2^n+1倍的插帧，所以FILM插帧不能把24FPS的视频插帧到100FPS

**Comment by HebeiFast** [comment]
由于davis publish出来是图片的格式，我们实际默认25fps来插值到100fps. 但是这并不会影响最终的event的生成，这只是个时间戳对应的问题。

**Comment by sove45** [comment]
> 由于davis publish出来是图片的格式，我们实际默认25fps来插值到100fps. 但是这并不会影响最终的event的生成，这只是个时间戳对应的问题。

![80efa03c7d12df3ffa6ffbab3c42c926](https://github.com/user-attachments/assets/45a7fa70-a273-4974-804d-8e91978fd1a7)
https://github.com/google-research/frame-interpolation
FILMGitHub主页如上，作者说输出帧的扩充倍数如下
![bfa726424cc3bf46803cc57ac6c99ff6](https://github.com/user-attachments/assets/9fc0857d-e0a9-472b-9972-561600173ff1)
所以25fps也不能扩充到100fps
麻烦您分享一下times_to_interpolat所采用的值
